const buildHairSpec = ({
  view = "three_quarter",
  lengthLabel,
  length,
  silhouette,
  density = "medium",
  volume = "natural",
  bangsType = "none",
  bangLength = "no bangs",
  forehead = "forehead remains mostly visible",
  eyebrow = "does not cover eyebrows",
  parting = "unclear",
  temple = "natural temple coverage",
  ear = "ears partially visible",
  cheek = "hair follows the cheek line naturally",
  sideburn = "natural sideburns",
  sideVolume = "natural side volume",
  rootLift = "natural root lift",
  crownVolume = "natural crown volume",
  flow = "natural hair flow",
  endLength,
  endShape,
  curl = "minimal inward bend",
  layering = "subtle layering",
  baseTexture = "straight",
  wave = "mostly straight with soft movement",
  curlSize = "none to loose",
  strand = "natural strand separation",
  finish = "natural_shine",
  baseColor = "natural black",
  undertone = "neutral",
  highlights = "none",
  variation = "even color from root to end",
  traits,
  avoid,
  brief,
}) => ({
  visibleView: view,
  overall: {
    lengthLabel,
    exactLengthDescription: length,
    outerSilhouette: silhouette,
    density,
    overallVolume: volume,
  },
  front: {
    bangsType,
    bangLength,
    foreheadCoverage: forehead,
    eyebrowInteraction: eyebrow,
    partingStart: parting,
    hairlineInstruction: "preserve the base person's original hairline height and forehead shape",
  },
  sides: {
    templeShape: temple,
    earCoverage: ear,
    cheekboneFlow: cheek,
    sideburnShape: sideburn,
    sideVolume,
  },
  crown: {
    parting,
    rootLift,
    crownVolume,
    flowDirection: flow,
  },
  ends: {
    endLength: endLength || length,
    endShape,
    curlDirection: curl,
    layeringAtEnds: layering,
  },
  texture: {
    baseTexture,
    wavePattern: wave,
    curlSize,
    strandDefinition: strand,
    finish,
  },
  color: {
    baseColor,
    undertone,
    highlights,
    rootToEndVariation: variation,
  },
  distinctiveTraits: traits,
  doNotSimplify: avoid,
  identitySafeAdaptation: [
    "preserve the base person's face shape, eyes, nose, mouth, skin, expression, and pose",
    "preserve the base person's original hairline height unless a very small natural blend is required",
    "adapt bangs and side volume conservatively if they would cover the eyes or change perceived face width",
    "do not alter clothing, background, lighting direction, crop, or camera angle",
  ],
  generationBrief: brief,
  confidence: { front: 8, sides: 7, back: 3, color: 8 },
});

const preset = (id, name, category, tags, args) => ({
  id,
  name,
  category,
  tags,
  thumbnail: `/style-presets/${id}.webp?v=real-20260504`,
  styleKeywords: tags.slice(0, 3).join(", "),
  hairSpec: buildHairSpec(args),
});

export const STYLE_PRESETS = [
  preset("see-through-layered", "시스루 뱅 레이어드컷", "women", ["여성", "롱", "레이어드", "앞머리"], {
    lengthLabel: "long",
    length: "long hair falling below the shoulders toward the chest",
    silhouette: "soft vertical layered silhouette with face-framing pieces",
    bangsType: "see_through",
    bangLength: "airy strands lightly touching the eyebrows",
    forehead: "about 40 percent visible through sparse bangs",
    eyebrow: "lightly touches but does not hide eyebrows",
    parting: "center",
    cheek: "face-framing layers curve softly near the cheekbones",
    endShape: "feathered ends with soft inward movement",
    baseTexture: "soft_wave",
    wave: "loose S-shaped movement through mid-lengths and ends",
    traits: ["airy see-through bangs", "long face-framing layers", "soft S-wave ends", "natural crown volume", "light feathered tips"],
    avoid: ["do not make thick blunt bangs", "do not turn into a round bob", "do not remove face-framing layers"],
    brief: "Apply long layered hair with airy see-through bangs lightly touching the eyebrows. Add soft face-framing layers and loose S-wave movement through the ends.",
  }),
  preset("hush-cut", "허쉬컷", "women", ["여성", "미디엄", "레이어드", "트렌디"], {
    lengthLabel: "medium",
    length: "medium length around the collarbone",
    silhouette: "shaggy layered silhouette with airy disconnected ends",
    bangsType: "curtain",
    bangLength: "long curtain pieces blending into cheek-length layers",
    forehead: "center forehead visible through a soft opening",
    parting: "center",
    cheek: "cheek-length layers open outward then taper down",
    sideVolume: "light airy side volume",
    endShape: "wispy outward flicked ends",
    baseTexture: "soft_wave",
    wave: "irregular soft bends with airy texture",
    traits: ["shaggy airy layers", "curtain fringe", "wispy outward ends", "collarbone length", "light textured movement"],
    avoid: ["do not make a heavy blunt cut", "do not smooth into one-length hair", "do not over-round the sides"],
    brief: "Apply a collarbone-length hush cut with airy shaggy layers and curtain fringe. Keep the ends wispy with slight outward flicks.",
  }),
  preset("tassel-bob", "태슬컷", "women", ["여성", "숏", "단발", "스트레이트"], {
    lengthLabel: "short",
    length: "straight bob ending near the jawline to lower chin",
    silhouette: "clean compact bob silhouette with a crisp bottom line",
    bangsType: "none",
    parting: "center",
    ear: "ears mostly covered by straight side panels",
    cheek: "side hair falls cleanly beside the jaw without puffiness",
    endShape: "sharp blunt tassel-like ends",
    baseTexture: "straight",
    wave: "sleek straight hair with minimal bend",
    traits: ["jaw-length clean bob", "sharp blunt ends", "sleek straight texture", "minimal side volume", "center part"],
    avoid: ["do not add waves", "do not make rounded mushroom volume", "do not feather the ends"],
    brief: "Apply a sleek jaw-length tassel bob with a clean blunt bottom line and center part.",
  }),
  preset("medium-c-curl", "중단발 C컬", "women", ["여성", "미디엄", "C컬", "단발"], {
    lengthLabel: "medium",
    length: "medium bob ending around the shoulders",
    silhouette: "soft shoulder-length bob with gentle inward curve",
    bangsType: "side_swept",
    bangLength: "soft side pieces near eyebrow to cheek length",
    forehead: "forehead mostly visible",
    parting: "left",
    cheek: "side hair curves inward along cheeks",
    endShape: "rounded inward C-curl at the ends",
    curl: "inward C-curl",
    baseTexture: "soft_wave",
    wave: "smooth straight body with curled-in ends",
    traits: ["shoulder-length bob", "inward C-curl ends", "soft side fringe", "smooth natural shine", "gentle volume"],
    avoid: ["do not make strong S-waves", "do not make a blunt straight bob", "do not hide the face with heavy sides"],
    brief: "Apply a shoulder-length medium bob with smooth body and inward C-curl ends.",
  }),
  preset("long-s-curl", "긴 레이어드 S컬", "women", ["여성", "롱", "S컬", "웨이브"], {
    lengthLabel: "long",
    length: "long hair falling to the upper chest",
    silhouette: "long layered silhouette with flowing waves",
    bangsType: "curtain",
    bangLength: "curtain pieces around cheekbone length",
    forehead: "forehead visible through center opening",
    parting: "center",
    endShape: "layered ends with flowing S-curls",
    baseTexture: "strong_wave",
    wave: "large S-shaped waves from mid-length to ends",
    curlSize: "large loose curls",
    traits: ["long flowing layers", "large S-curls", "cheekbone curtain pieces", "soft glossy finish", "balanced side volume"],
    avoid: ["do not make tight ringlets", "do not flatten the waves", "do not shorten above shoulders"],
    brief: "Apply long layered hair with large flowing S-curls from the mid-lengths to the ends.",
  }),
  preset("hippie-perm", "히피펌", "women", ["여성", "롱", "펌/웨이브", "컬"], {
    lengthLabel: "long",
    length: "long hair below the shoulders",
    silhouette: "full textured silhouette with dense waves",
    density: "thick",
    volume: "full",
    bangsType: "see_through",
    bangLength: "curly airy bangs near eyebrow length",
    forehead: "partly visible through separated curls",
    sideVolume: "full textured side volume",
    crownVolume: "full crown volume",
    endShape: "textured curly ends",
    baseTexture: "curl",
    wave: "dense small waves throughout the hair",
    curlSize: "small to medium curls",
    strand: "clearly separated curly strands",
    traits: ["dense hippie perm texture", "full side volume", "small separated curls", "curly airy bangs", "long textured ends"],
    avoid: ["do not smooth into loose waves", "do not remove curl density", "do not create a polished straight finish"],
    brief: "Apply a long hippie perm with dense small-to-medium curls and full textured volume.",
  }),
  preset("water-wave", "물결펌", "women", ["여성", "미디엄", "펌/웨이브", "물결"], {
    lengthLabel: "medium",
    length: "medium hair around shoulder to collarbone length",
    silhouette: "soft wavy silhouette with even ripple movement",
    bangsType: "none",
    parting: "center",
    endShape: "softly waved ends",
    baseTexture: "strong_wave",
    wave: "regular water-ripple waves from upper mid-length to ends",
    curlSize: "medium waves",
    traits: ["regular ripple waves", "medium length", "center part", "soft side drape", "natural glossy finish"],
    avoid: ["do not make tight curls", "do not make straight C-curl only", "do not over-puff the crown"],
    brief: "Apply medium-length water-wave hair with regular ripple waves from the mid-lengths to the ends.",
  }),
  preset("sleek-straight", "슬릭 스트레이트", "women", ["여성", "롱", "스트레이트", "슬릭"], {
    lengthLabel: "long",
    length: "long straight hair falling below the shoulders",
    silhouette: "narrow sleek vertical silhouette",
    volume: "flat",
    bangsType: "none",
    parting: "center",
    sideVolume: "flat close side volume",
    crownVolume: "flat smooth crown",
    endShape: "straight smooth ends",
    baseTexture: "straight",
    wave: "pin-straight smooth strands",
    finish: "glossy",
    traits: ["sleek center part", "flat smooth crown", "long straight panels", "glossy finish", "minimal side volume"],
    avoid: ["do not add waves", "do not add fluffy volume", "do not create bangs"],
    brief: "Apply long sleek straight hair with a clean center part, glossy finish, and minimal side volume.",
  }),
  preset("ash-brown-long-wave", "애쉬 브라운 롱 웨이브", "women", ["여성", "롱", "컬러", "웨이브"], {
    lengthLabel: "long",
    length: "long hair reaching the chest",
    silhouette: "soft long wave silhouette",
    bangsType: "curtain",
    parting: "center",
    endShape: "loose waved ends",
    baseTexture: "soft_wave",
    wave: "large loose waves through lower half",
    baseColor: "ash brown",
    undertone: "cool muted brown",
    highlights: "subtle lighter ash brown ribbons",
    variation: "slightly darker roots fading to soft ash brown ends",
    traits: ["cool ash brown color", "long loose waves", "subtle highlights", "curtain front pieces", "soft glossy finish"],
    avoid: ["do not turn black", "do not make warm orange brown", "do not create tight curls"],
    brief: "Apply long loose waves in a cool ash brown color with subtle lighter ribbons.",
  }),
  preset("black-short-bob", "블랙 단발", "women", ["여성", "숏", "단발", "블랙"], {
    lengthLabel: "short",
    length: "short bob ending between chin and jaw",
    silhouette: "compact black bob with slight inward curve",
    bangsType: "full",
    bangLength: "soft full bangs just above eyebrows",
    forehead: "mostly covered by bangs",
    eyebrow: "bangs sit just above the eyebrows",
    parting: "none",
    ear: "ears covered",
    endShape: "subtle inward curved ends",
    baseTexture: "straight",
    baseColor: "natural deep black",
    traits: ["deep black bob", "soft full bangs", "chin-to-jaw length", "slight inward curve", "compact silhouette"],
    avoid: ["do not make see-through bangs", "do not add waves", "do not make long hair"],
    brief: "Apply a compact deep black short bob with soft full bangs just above the eyebrows and slightly inward-curved ends.",
  }),
  preset("red-brown-wave", "레드 브라운 웨이브", "women", ["여성", "미디엄", "컬러", "웨이브"], {
    lengthLabel: "medium",
    length: "medium length around the collarbone",
    silhouette: "soft wavy medium silhouette",
    bangsType: "curtain",
    parting: "center",
    endShape: "soft waved ends",
    baseTexture: "soft_wave",
    wave: "loose waves around cheeks and ends",
    baseColor: "red brown",
    undertone: "warm copper red brown",
    highlights: "subtle warm red reflections",
    variation: "slightly deeper roots with warm red brown lengths",
    traits: ["warm red brown color", "medium loose waves", "curtain fringe", "soft cheek movement", "natural shine"],
    avoid: ["do not make vivid neon red", "do not flatten the waves", "do not cover the eyes"],
    brief: "Apply a medium-length warm red brown wave style with soft curtain fringe and loose cheek-to-end waves.",
  }),
  preset("leaf-cut", "리프컷", "men", ["남성", "미디엄", "가르마", "트렌디"], {
    lengthLabel: "medium",
    length: "medium men's hair with front pieces around eye to cheek level",
    silhouette: "leaf-shaped parted silhouette with soft side flow",
    bangsType: "curtain",
    bangLength: "long parted front pieces around eyebrow to cheekbone",
    forehead: "forehead partly visible through part",
    parting: "center",
    temple: "soft temple coverage",
    ear: "ears partially covered",
    cheek: "front pieces sweep away from the face like leaves",
    endShape: "soft tapered ends",
    baseTexture: "soft_wave",
    wave: "gentle natural bends in the front and sides",
    traits: ["center parted long front", "leaf-like side sweep", "soft medium length", "partly covered ears", "natural airy volume"],
    avoid: ["do not make short crop", "do not add heavy curls", "do not cover both eyes"],
    brief: "Apply a men's leaf cut with medium length, center-parted long front pieces, and soft side flow.",
  }),
  preset("comma-hair", "가르마펌", "men", ["남성", "미디엄", "펌/웨이브", "가르마"], {
    lengthLabel: "medium",
    length: "medium men's hair with front fringe around eyebrow length",
    silhouette: "parted soft volume silhouette",
    bangsType: "side_swept",
    bangLength: "front pieces curve near eyebrow level",
    forehead: "forehead visible along the part",
    parting: "left",
    cheek: "front hair curves softly away from one side",
    crownVolume: "natural lifted crown",
    endShape: "soft tapered ends",
    baseTexture: "soft_wave",
    wave: "gentle perm bends around the part and fringe",
    traits: ["left part", "soft comma-shaped fringe", "natural root lift", "clean tapered sides", "gentle perm texture"],
    avoid: ["do not make flat straight bangs", "do not create tight curls", "do not shave the sides too high"],
    brief: "Apply a men's parted perm with a soft comma-shaped fringe and natural root lift.",
  }),
  preset("shadow-perm", "쉐도우펌", "men", ["남성", "미디엄", "펌/웨이브", "볼륨"], {
    lengthLabel: "medium",
    length: "medium men's hair with fringe near eyebrows",
    silhouette: "rounded textured volume with controlled sides",
    density: "thick",
    volume: "full",
    bangsType: "full",
    bangLength: "textured fringe around eyebrow level",
    forehead: "mostly covered by separated fringe",
    parting: "none",
    sideVolume: "controlled full side volume",
    crownVolume: "full textured crown",
    endShape: "textured tapered ends",
    baseTexture: "soft_wave",
    wave: "soft shadow perm waves throughout top and fringe",
    traits: ["textured eyebrow fringe", "full top volume", "soft shadow waves", "controlled side volume", "rounded but not helmet-like shape"],
    avoid: ["do not make pin-straight hair", "do not over-cover the eyes", "do not make tight curls"],
    brief: "Apply a men's shadow perm with full textured crown volume and separated eyebrow-level fringe.",
  }),
  preset("ivy-league", "아이비리그컷", "men", ["남성", "숏", "클래식", "깔끔"], {
    lengthLabel: "short",
    length: "short neat men's cut with slightly longer top",
    silhouette: "clean compact silhouette with tapered sides",
    bangsType: "none",
    forehead: "forehead fully visible",
    parting: "left",
    temple: "clean tapered temples",
    ear: "ears fully visible",
    sideburn: "short neat sideburns",
    crownVolume: "low natural crown",
    endShape: "short tapered ends",
    baseTexture: "straight",
    traits: ["short tapered sides", "neat side part", "forehead visible", "slightly longer combed top", "clean professional shape"],
    avoid: ["do not add long bangs", "do not cover ears", "do not add waves or curls"],
    brief: "Apply a clean Ivy League cut with short tapered sides, a neat side part, and a slightly longer combed top.",
  }),
  preset("crop-cut", "크롭컷", "men", ["남성", "숏", "크롭", "깔끔"], {
    lengthLabel: "short",
    length: "very short men's crop with short fringe",
    silhouette: "compact close-cropped silhouette",
    bangsType: "full",
    bangLength: "very short blunt textured fringe above the forehead",
    forehead: "forehead mostly visible below short fringe",
    eyebrow: "fringe stays far above eyebrows",
    parting: "none",
    temple: "tight clean temples",
    ear: "ears fully visible",
    sideVolume: "flat close sides",
    crownVolume: "low textured top",
    endShape: "short textured ends",
    baseTexture: "straight",
    traits: ["very short crop", "short textured fringe", "tight sides", "low top texture", "clean forehead"],
    avoid: ["do not make long bangs", "do not add side volume", "do not cover ears"],
    brief: "Apply a short crop cut with tight sides and a short textured fringe well above the eyebrows.",
  }),
  preset("dandy-cut", "댄디컷", "men", ["남성", "숏", "댄디", "깔끔"], {
    lengthLabel: "short",
    length: "short to medium neat men's hair around eyebrow fringe length",
    silhouette: "smooth tidy dandy silhouette",
    bangsType: "side_swept",
    bangLength: "soft fringe near eyebrows but not covering eyes",
    forehead: "partly visible",
    parting: "left",
    temple: "neatly covered temples",
    ear: "ears partly visible",
    crownVolume: "natural smooth crown",
    endShape: "neatly tapered ends",
    baseTexture: "straight",
    wave: "mostly straight with slight styling bend",
    traits: ["soft side-swept fringe", "tidy natural volume", "neatly tapered sides", "smooth clean texture", "partly visible forehead"],
    avoid: ["do not make messy waves", "do not shave too aggressively", "do not cover the eyes"],
    brief: "Apply a neat men's dandy cut with soft side-swept fringe, smooth natural volume, and neatly tapered sides.",
  }),
  preset("wolf-cut", "울프컷", "men", ["남성", "미디엄", "레이어드", "트렌디"], {
    lengthLabel: "medium",
    length: "medium cut with textured top and longer nape",
    silhouette: "wolf cut silhouette with shaggy layers and extended nape",
    bangsType: "other",
    bangLength: "textured fringe around eyebrow level",
    forehead: "partly visible through separated texture",
    parting: "none",
    ear: "ears partly visible through layers",
    endShape: "shaggy tapered nape ends",
    layering: "heavy shag layering",
    baseTexture: "soft_wave",
    wave: "messy textured bends",
    traits: ["longer nape", "textured top", "separated fringe", "shaggy sides", "tapered layered ends"],
    avoid: ["do not make clean bob", "do not remove nape length", "do not make sleek straight style"],
    brief: "Apply a wolf cut with textured top, separated fringe, and a longer tapered nape.",
  }),
  preset("two-block-dandy", "투블럭 댄디", "men", ["남성", "숏", "투블럭", "깔끔"], {
    lengthLabel: "short",
    length: "short two-block sides with neat medium top",
    silhouette: "clean two-block silhouette with smooth top",
    bangsType: "side_swept",
    bangLength: "soft side fringe around eyebrow level",
    forehead: "partly visible",
    parting: "left",
    temple: "short controlled two-block temple",
    ear: "ears mostly visible",
    sideVolume: "flat clean sides",
    crownVolume: "natural smooth top volume",
    endShape: "clean tapered ends",
    baseTexture: "straight",
    traits: ["two-block sides", "soft dandy fringe", "clean ears", "smooth top", "neat side part"],
    avoid: ["do not make high undercut too severe", "do not add messy curls", "do not cover the eyes"],
    brief: "Apply a clean two-block dandy cut with short controlled sides and a smooth side-swept top.",
  }),
  preset("ash-gray", "애쉬 그레이 컬러", "unisex", ["공용", "컬러", "애쉬", "트렌디"], {
    lengthLabel: "medium",
    length: "medium hair around the neck to shoulder length",
    silhouette: "clean medium silhouette with light texture",
    bangsType: "curtain",
    parting: "center",
    endShape: "soft textured ends",
    baseTexture: "straight",
    wave: "straight to softly bent texture",
    baseColor: "ash gray",
    undertone: "cool gray",
    highlights: "subtle silver-gray highlights",
    variation: "slightly darker roots with smoky ash gray lengths",
    traits: ["cool ash gray color", "smoky darker roots", "soft medium texture", "muted silver highlights", "clean center part"],
    avoid: ["do not make warm blonde", "do not make solid black", "do not add vivid blue"],
    brief: "Apply a medium clean style in cool ash gray with smoky darker roots and subtle silver highlights.",
  }),
  preset("pixie-cut", "픽시컷", "women", ["여성", "숏", "커트", "깔끔"], {
    lengthLabel: "short",
    length: "very short pixie cut around the ears",
    silhouette: "short airy pixie silhouette with tapered sides",
    bangsType: "side_swept",
    bangLength: "short side fringe above eyebrow to temple",
    forehead: "forehead mostly visible",
    parting: "right",
    temple: "softly tapered temple hair",
    ear: "ears fully visible",
    crownVolume: "light textured crown",
    endShape: "short feathered ends",
    baseTexture: "straight",
    strand: "piecey short separation",
    traits: ["short pixie outline", "visible ears", "side-swept fringe", "piecey crown texture", "soft tapered sides"],
    avoid: ["do not leave bob-length sides", "do not hide ears", "do not add long curls"],
    brief: "Apply a short pixie cut with visible ears, side-swept fringe, and piecey crown texture.",
  }),
  preset("layered-bob", "레이어드 보브", "women", ["여성", "숏", "단발", "레이어드"], {
    lengthLabel: "short",
    length: "short bob around chin to neck length",
    silhouette: "layered bob silhouette with soft roundness",
    bangsType: "curtain",
    bangLength: "soft cheek-length curtain pieces",
    parting: "center",
    ear: "ears mostly covered",
    cheek: "layers curve gently along cheek and jaw",
    endShape: "light layered bob ends",
    baseTexture: "soft_wave",
    wave: "soft inward and outward bends through layers",
    traits: ["short layered bob", "soft curtain front", "light rounded volume", "textured ends", "face-framing side layers"],
    avoid: ["do not make one-length blunt bob", "do not add tight curls", "do not flatten the sides"],
    brief: "Apply a short layered bob with soft curtain front pieces and light rounded volume.",
  }),
  preset("short-c-curl-bob", "단발 C컬", "women", ["여성", "숏", "C컬", "단발"], {
    lengthLabel: "short",
    length: "short bob ending near the lower chin",
    silhouette: "compact bob with rounded inward ends",
    bangsType: "see_through",
    bangLength: "airy eyebrow-length bangs",
    forehead: "partly visible through sparse bangs",
    parting: "none",
    ear: "ears covered by bob side panels",
    endShape: "rounded inward C-curl ends",
    curl: "inward C-curl",
    baseTexture: "soft_wave",
    wave: "smooth bob with curled-in ends",
    traits: ["short C-curl bob", "airy bangs", "rounded inward ends", "compact side panels", "soft shine"],
    avoid: ["do not create long waves", "do not make blunt straight ends", "do not over-cover eyes"],
    brief: "Apply a short bob with airy bangs and rounded inward C-curl ends.",
  }),
  preset("long-straight-bangs", "긴 생머리 풀뱅", "women", ["여성", "롱", "스트레이트", "앞머리"], {
    lengthLabel: "long",
    length: "long straight hair below the shoulders",
    silhouette: "smooth long straight silhouette with full bangs",
    bangsType: "full",
    bangLength: "full bangs just above or lightly touching eyebrows",
    forehead: "forehead mostly covered",
    eyebrow: "bangs align near eyebrows without covering eyes",
    parting: "none",
    sideVolume: "smooth low side volume",
    crownVolume: "smooth natural crown",
    endShape: "straight clean ends",
    baseTexture: "straight",
    wave: "straight hair with minimal bend",
    traits: ["full straight bangs", "long smooth hair", "low side volume", "clean ends", "natural shine"],
    avoid: ["do not make see-through bangs", "do not add waves", "do not part the bangs"],
    brief: "Apply long smooth straight hair with full eyebrow-level bangs and clean ends.",
  }),
  preset("balayage-wave", "발레아쥬 웨이브", "women", ["여성", "롱", "컬러", "웨이브"], {
    lengthLabel: "long",
    length: "long hair reaching the upper chest",
    silhouette: "long beachy wave silhouette",
    bangsType: "none",
    parting: "center",
    endShape: "soft wavy layered ends",
    baseTexture: "soft_wave",
    wave: "loose beachy waves from mid-lengths to ends",
    baseColor: "dark brown with beige balayage",
    undertone: "neutral brown and beige",
    highlights: "soft beige balayage ribbons concentrated near mid-lengths and ends",
    variation: "dark roots blended into lighter beige-brown ends",
    traits: ["beige balayage highlights", "dark natural roots", "long loose waves", "soft blended color", "no harsh stripe lines"],
    avoid: ["do not create harsh stripe highlights", "do not make solid black", "do not make tight curls"],
    brief: "Apply long loose beachy waves with dark brown roots blended into beige balayage highlights.",
  }),
  preset("rose-brown-lob", "로즈 브라운 로브", "women", ["여성", "미디엄", "컬러", "단발"], {
    lengthLabel: "medium",
    length: "long bob around collarbone length",
    silhouette: "soft lob silhouette with light ends",
    bangsType: "none",
    parting: "center",
    endShape: "soft slightly textured lob ends",
    baseTexture: "soft_wave",
    wave: "very loose waves with natural movement",
    baseColor: "rose brown",
    undertone: "muted pink brown",
    highlights: "subtle rosy reflections",
    variation: "soft rose brown from roots to ends",
    traits: ["rose brown color", "collarbone lob", "very loose waves", "center part", "soft textured ends"],
    avoid: ["do not make vivid pink", "do not add heavy curls", "do not shorten above chin"],
    brief: "Apply a collarbone-length lob with very loose waves and muted rose brown color.",
  }),
  preset("mullet-shag", "멀릿 샤그", "unisex", ["공용", "미디엄", "레이어드", "트렌디"], {
    lengthLabel: "medium",
    length: "shorter front and sides with longer nape",
    silhouette: "mullet shag silhouette with longer back and textured top",
    bangsType: "other",
    bangLength: "textured fringe around eyebrow length",
    forehead: "partly covered by separated texture",
    parting: "none",
    ear: "ears partly visible through layers",
    endShape: "shaggy tapered nape ends",
    layering: "heavy shag layering",
    baseTexture: "soft_wave",
    wave: "messy textured bends",
    traits: ["longer nape", "textured top", "separated fringe", "shaggy sides", "tapered layered ends"],
    avoid: ["do not make clean bob", "do not remove nape length", "do not make sleek straight style"],
    brief: "Apply a mullet shag with textured top, separated fringe, and a longer tapered nape.",
  }),
  preset("soft-mash", "소프트 마쉬", "men", ["남성", "미디엄", "볼륨", "트렌디"], {
    lengthLabel: "medium",
    length: "medium men's hair with soft fringe near eyebrows",
    silhouette: "soft rounded mash silhouette with natural texture",
    bangsType: "full",
    bangLength: "soft fringe near eyebrow length",
    forehead: "mostly covered but with separated texture",
    parting: "none",
    ear: "ears partly covered",
    sideVolume: "natural rounded side volume",
    crownVolume: "natural full crown",
    endShape: "soft tapered ends",
    baseTexture: "soft_wave",
    wave: "light natural bends through fringe and top",
    traits: ["soft mash fringe", "rounded natural volume", "light texture", "partly covered ears", "gentle top movement"],
    avoid: ["do not make hard bowl cut", "do not make tight curls", "do not cover eyes fully"],
    brief: "Apply a soft mash men's style with rounded natural volume, light texture, and eyebrow-level separated fringe.",
  }),
  preset("regent-cut", "리젠트컷", "men", ["남성", "숏", "볼륨", "클래식"], {
    lengthLabel: "short",
    length: "short sides with longer lifted front top",
    silhouette: "clean lifted front silhouette with tapered sides",
    bangsType: "none",
    forehead: "forehead fully visible",
    parting: "none",
    temple: "clean tapered temples",
    ear: "ears fully visible",
    crownVolume: "high front volume with controlled crown",
    rootLift: "strong upward lift at the front",
    flow: "front hair lifted upward and slightly back",
    endShape: "short clean tapered ends",
    baseTexture: "straight",
    traits: ["lifted front volume", "short tapered sides", "forehead visible", "clean classic outline", "controlled top"],
    avoid: ["do not create bangs", "do not cover forehead", "do not add long side hair"],
    brief: "Apply a clean regent cut with short tapered sides and strong upward front volume.",
  }),
  preset("buzz-cut", "버즈컷", "men", ["남성", "숏", "클래식", "깔끔"], {
    lengthLabel: "short",
    length: "very short even buzz cut",
    silhouette: "close-cropped head-hugging silhouette",
    bangsType: "none",
    forehead: "forehead fully visible",
    parting: "none",
    temple: "very short clean temples",
    ear: "ears fully visible",
    sideVolume: "flat close sides",
    crownVolume: "flat very short crown",
    endShape: "uniform clipped ends",
    baseTexture: "straight",
    traits: ["very short even length", "close-cropped sides", "forehead visible", "ears visible", "minimal texture"],
    avoid: ["do not leave long fringe", "do not add waves", "do not add volume"],
    brief: "Apply a very short even buzz cut with close-cropped sides and crown.",
  }),
  preset("undercut-slickback", "언더컷 슬릭백", "men", ["남성", "숏", "슬릭", "클래식"], {
    lengthLabel: "short",
    length: "short sides with longer top slicked back",
    silhouette: "slicked-back top with clean undercut sides",
    bangsType: "none",
    forehead: "forehead fully visible",
    parting: "none",
    temple: "close undercut temples",
    ear: "ears fully visible",
    sideVolume: "flat close sides",
    crownVolume: "controlled slick top volume",
    flow: "top hair combed back from the forehead",
    finish: "glossy",
    traits: ["slicked-back top", "close undercut sides", "forehead visible", "glossy finish", "sharp clean outline"],
    avoid: ["do not add bangs", "do not make fluffy top", "do not cover ears"],
    brief: "Apply an undercut slick-back with close sides and the longer top combed back from the forehead.",
  }),
  preset("middle-part-men", "남자 중단발 가르마", "men", ["남성", "미디엄", "가르마", "롱"], {
    lengthLabel: "medium",
    length: "medium-long men's hair reaching the neck",
    silhouette: "center-parted medium silhouette with soft drape",
    bangsType: "curtain",
    bangLength: "long center-parted pieces around cheek level",
    forehead: "forehead visible through center part",
    parting: "center",
    ear: "ears mostly covered",
    cheek: "long front pieces drape along cheeks",
    endShape: "soft neck-length ends",
    baseTexture: "soft_wave",
    wave: "natural soft bends through longer hair",
    traits: ["neck-length men's hair", "center part", "long cheek-level front pieces", "covered ears", "soft natural bends"],
    avoid: ["do not cut short", "do not create tight perm", "do not cover both eyes"],
    brief: "Apply medium-long men's center-part hair reaching the neck, with cheek-level curtain pieces and soft natural bends.",
  }),
  preset("messy-spiky", "메시 스파이키", "men", ["남성", "숏", "볼륨", "트렌디"], {
    lengthLabel: "short",
    length: "short men's hair with textured top",
    silhouette: "short textured silhouette with lifted spikes",
    bangsType: "none",
    forehead: "forehead mostly visible",
    parting: "none",
    temple: "short clean temples",
    ear: "ears visible",
    crownVolume: "high textured top volume",
    rootLift: "upward messy root lift",
    flow: "short strands lifted upward in varied directions",
    endShape: "piecey textured tips",
    baseTexture: "straight",
    strand: "piecey separated strands",
    finish: "matte",
    traits: ["messy lifted spikes", "short clean sides", "piecey matte texture", "forehead visible", "high top texture"],
    avoid: ["do not make smooth dandy hair", "do not add long bangs", "do not create curls"],
    brief: "Apply a short messy spiky style with lifted piecey top texture and clean sides.",
  }),
  preset("silver-short", "실버 숏컷", "unisex", ["공용", "숏", "컬러", "실버"], {
    lengthLabel: "short",
    length: "short textured hair around ears",
    silhouette: "short clean silhouette with textured top",
    bangsType: "side_swept",
    bangLength: "short side fringe above eyebrows",
    forehead: "mostly visible",
    ear: "ears visible",
    crownVolume: "light textured crown",
    endShape: "short tapered ends",
    baseTexture: "straight",
    baseColor: "silver gray",
    undertone: "cool metallic silver",
    highlights: "pale silver highlights",
    variation: "slightly darker roots with silver tips",
    traits: ["silver gray color", "short textured top", "visible ears", "cool metallic tone", "short side fringe"],
    avoid: ["do not make warm blonde", "do not make long hair", "do not add heavy curls"],
    brief: "Apply a short textured cut in cool silver gray with slightly darker roots and pale silver highlights.",
  }),
  preset("blue-black", "블루블랙 스트레이트", "unisex", ["공용", "컬러", "스트레이트", "블랙"], {
    lengthLabel: "medium",
    length: "medium straight hair around shoulder length",
    silhouette: "smooth straight medium silhouette",
    bangsType: "none",
    parting: "center",
    endShape: "straight clean ends",
    baseTexture: "straight",
    baseColor: "blue black",
    undertone: "cool blue-black sheen",
    highlights: "subtle blue sheen visible in highlights",
    variation: "nearly black roots and lengths with blue reflective tone",
    traits: ["blue-black color", "straight smooth texture", "center part", "cool reflective sheen", "clean ends"],
    avoid: ["do not make bright blue", "do not make warm brown", "do not add curls"],
    brief: "Apply smooth medium straight hair with a cool blue-black reflective sheen.",
  }),
  preset("lavender-bob", "라벤더 보브", "unisex", ["공용", "숏", "컬러", "단발"], {
    lengthLabel: "short",
    length: "bob length around chin to jaw",
    silhouette: "soft bob silhouette with clean sides",
    bangsType: "curtain",
    bangLength: "soft curtain front around cheekbone",
    parting: "center",
    endShape: "soft blunt bob ends",
    baseTexture: "straight",
    baseColor: "lavender ash",
    undertone: "cool muted purple ash",
    highlights: "subtle pale lavender highlights",
    variation: "slightly deeper roots with muted lavender lengths",
    traits: ["lavender ash color", "short bob", "soft curtain front", "cool muted tone", "clean blunt ends"],
    avoid: ["do not make vivid purple", "do not add long waves", "do not make warm pink"],
    brief: "Apply a short bob in muted lavender ash with a soft curtain front and clean blunt ends.",
  }),
  preset("orange-copper-wave", "오렌지 코퍼 웨이브", "unisex", ["공용", "컬러", "웨이브", "트렌디"], {
    lengthLabel: "medium",
    length: "medium hair around collarbone length",
    silhouette: "medium wavy silhouette with bright color",
    bangsType: "curtain",
    parting: "center",
    endShape: "loose wavy ends",
    baseTexture: "soft_wave",
    wave: "loose waves through sides and ends",
    baseColor: "orange copper",
    undertone: "warm vivid copper orange",
    highlights: "soft golden copper reflections",
    variation: "slightly darker copper roots with brighter ends",
    traits: ["orange copper color", "medium loose waves", "warm vivid tone", "curtain front", "soft golden reflections"],
    avoid: ["do not make red brown only", "do not make neon orange", "do not flatten the waves"],
    brief: "Apply a medium loose wave style in warm orange copper with soft golden reflections.",
  }),
  preset("natural-curly", "내추럴 컬리", "unisex", ["공용", "미디엄", "컬", "펌/웨이브"], {
    lengthLabel: "medium",
    length: "medium curly hair around neck to shoulder length",
    silhouette: "rounded natural curly silhouette",
    density: "thick",
    volume: "full",
    bangsType: "other",
    bangLength: "curly front pieces around eyebrow to forehead level",
    forehead: "partly visible between curls",
    parting: "unclear",
    sideVolume: "full natural curl volume",
    crownVolume: "full natural crown",
    endShape: "springy curly ends",
    baseTexture: "curl",
    wave: "natural curl pattern throughout",
    curlSize: "medium curls",
    strand: "defined separated curls",
    traits: ["natural medium curls", "rounded full volume", "defined curl clumps", "partly visible forehead", "springy ends"],
    avoid: ["do not straighten", "do not make loose waves only", "do not flatten the crown"],
    brief: "Apply medium natural curly hair with defined medium curl clumps, rounded full volume, and springy ends.",
  }),
  preset("wet-look", "웻룩", "unisex", ["공용", "숏", "슬릭", "트렌디"], {
    lengthLabel: "short",
    length: "short to medium hair slicked back from the face",
    silhouette: "close wet-look silhouette with combed-back flow",
    bangsType: "none",
    forehead: "forehead fully visible",
    parting: "none",
    temple: "slick hair close to temples",
    ear: "ears visible or partly visible",
    sideVolume: "flat slick side volume",
    crownVolume: "low controlled crown",
    flow: "hair combed backward away from the face",
    finish: "wet",
    baseTexture: "wet",
    strand: "glossy separated wet strands",
    traits: ["wet glossy finish", "combed-back front", "flat slick sides", "visible forehead", "defined wet strands"],
    avoid: ["do not create dry fluffy volume", "do not add bangs", "do not make loose curls"],
    brief: "Apply a wet-look slick style with the front combed back, glossy separated strands, and flat controlled sides.",
  }),
  preset("soft-two-tone", "소프트 투톤", "unisex", ["공용", "컬러", "트렌디", "미디엄"], {
    lengthLabel: "medium",
    length: "medium hair around neck to shoulder length",
    silhouette: "medium layered silhouette with visible color contrast",
    bangsType: "curtain",
    parting: "center",
    endShape: "soft layered ends",
    baseTexture: "straight",
    wave: "straight to softly bent layers",
    baseColor: "dark brown with beige inner tone",
    undertone: "neutral dark brown and soft beige",
    highlights: "beige inner layer or face-framing panels",
    variation: "dark outer layer with lighter beige inner or front panels",
    traits: ["soft two-tone color", "dark outer layer", "beige inner panels", "medium layers", "center curtain front"],
    avoid: ["do not make harsh block stripes", "do not make single flat color", "do not over-brighten to platinum"],
    brief: "Apply a soft two-tone medium style with dark brown outer hair and subtle beige inner or face-framing panels.",
  }),
];

export const findStylePreset = (presetOrId) => {
  const id = typeof presetOrId === "string" ? presetOrId : presetOrId?.id;
  return STYLE_PRESETS.find((presetItem) => presetItem.id === id) || null;
};
